# Generated by Django 6.0.2 on 2026-05-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cliente_apellidos_remove_cliente_dui_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
