# Generated by Django 6.0.2 on 2026-05-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('costos', 'Costos'), ('gasto', 'Gasto')], max_length=20),
        ),
    ]
